- name: Installing Nginx
  hosts: localhost
  tasks:
  - name: Install Nginx
    become: yes
    ansible.builtin.package:
      name: nginx
      state: present
      use: dnf

  - name: Running the Nginx
    ansible.builtin.service:
      name: nginx
      state: started
